name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5
          check-latest: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: go test -v -race ./...
